version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: tesutoproject/api:0.2
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
          - .
  test:
    working_directory: ~/tmp
    docker:
      - image: tesutoproject/api:0.2
    steps:
      - run: ls -l
      - run: python manage.py test sample
workflows:
  version: 2
  api:
    jobs:
      - build
      - test:
          requires:
            - build
